COMPONENT_SRCDIRS := \
					res \
					lib \
					hal \
					test \
					def \
					drv/protocols/i2c \
					drv/3rd/bmp280 \
					drv/3rd/adxl345 \
					drv/audio \
					drv/battery	\
					drv/bluetooth \
					drv/display	\
					drv/input \
					drv/power	\
					drv/storage \
					drv/usb	\
					drv/wifi \
					drv/protocols/i2c \
					hal/temperature \
					hal/accelerometer \
					hal/peripherals \
					hal/modules \
					hal/audio \
					hal/battery \
					hal/bluetooth \
					hal/display \
					hal/input \
					hal/power \
					hal/storage \
					hal/pressure \
					hal/humidity \
					hal/temperature \
					hal/usb \
					hal/wifi \

COMPONENT_ADD_INCLUDEDIRS := \
					res/include \
					lib/include \
					hal/include \
					test/ \
					hal/peripherals/include \
					hal/modules/include \
					hal/temperature/include \
					hal/accelerometer/include \
					drv/include \
					drv/protocols/i2c/include \
					drv/3rd/bmp280/include \
					drv/3rd/adxl345/include \
					hal/peripherals/include \
					hal/modules/include \
					hal/audio/include \
					hal/battery/include \
					hal/bluetooth/include \
					hal/display/include \
					hal/input/include \
					hal/power/include \
					hal/storage/include \
					hal/pressure/include \
					hal/humidity/include \
					hal/temperature/include \
					hal/usb/include \
					hal/wifi/include \
					. \
